services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: vekant_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: vekant
      POSTGRES_USER: vekant
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vekant123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - vekant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vekant -d vekant"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vekant_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    # ports:
      # - "6379:6379"
    networks:
      - vekant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Laravel Backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: vekant_backend
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=vekant
      - DB_USERNAME=vekant
      - DB_PASSWORD=${DB_PASSWORD:-vekant123}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./back-end:/var/www
      - backend_storage:/var/www/storage
      - backend_cache:/var/www/bootstrap/cache
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vekant_network
    healthcheck:
      test: ["CMD", "php", "artisan", "migrate:status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: development
    container_name: vekant_frontend
    restart: unless-stopped
    volumes:
      - ./front-end/src:/app/src:ro
      - ./front-end/angular.json:/app/angular.json:ro
      - ./front-end/tsconfig.json:/app/tsconfig.json:ro
      - ./front-end/tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./front-end/tailwind.config.js:/app/tailwind.config.js:ro
    ports:
      - "4200:4200"
    networks:
      - vekant_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3

  # NGINX Proxy
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: vekant_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - backend_storage:/var/www/storage:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vekant_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_storage:
    driver: local
  backend_cache:
    driver: local

networks:
  vekant_network:
    driver: bridge